const $=s=>document.querySelector(s), apps={explorer:['File Explorer','📁'],browser:['Browser','🌐'],notepad:['Notepad','📝'],calculator:['Calculator','🧮'],photos:['Photos','🖼️'],store:['Microsoft Store','🛍️'],settings:['Settings','⚙️'],recycle:['Recycle Bin','♻️']};let account=JSON.parse(localStorage.getItem('win11sim-account')||'null'),z=10;
const hide=x=>x.classList.add('hidden'),show=x=>x.classList.remove('hidden');
setTimeout(()=>{hide($('#boot'));account?show($('#signin')):show($('#welcome'))},1200);
$('#welcomeNext').onclick=()=>{hide($('#welcome'));show($('#accountSetup'));$('#setupName').focus()};
$('#createAccount').onclick=()=>{let n=$('#setupName').value.trim(),p=$('#setupPassword').value;if(!n||!p)return alert('Enter a name and password.');account={name:n,password:p};localStorage.setItem('win11sim-account',JSON.stringify(account));hide($('#accountSetup'));loginScreen()};
function loginScreen(){$('#signinName').textContent=account.name;$('#signinPassword').value='';show($('#signin'));setTimeout(()=>$('#signinPassword').focus(),50)}
function login(){if($('#signinPassword').value!==account.password)return $('#signinError').textContent='Incorrect password';hide($('#signin'));show($('#os'));$('#startUserName').textContent=account.name;if(!localStorage.getItem('win11sim-welcomed')){localStorage.setItem('win11sim-welcomed','1');toast('Welcome, '+account.name+'!')}}
$('#signinButton').onclick=login;$('#signinPassword').onkeydown=e=>e.key==='Enter'&&login();$('#switchUser').onclick=()=>toast('One local account is supported in this demo.');
$('#pinnedApps').innerHTML=Object.entries(apps).map(([id,a])=>`<button data-open="${id}"><span>${a[1]}</span><small>${a[0]}</small></button>`).join('');
function body(id){if(id==='explorer')return '<div class="explorer-body"><aside class="sidebar"><button>🏠 Home</button><button>🖥️ This PC</button><button>📥 Downloads</button><button>📄 Documents</button><button>🖼️ Pictures</button></aside><div class="file-area"><h2>Home</h2><div class="file-grid"><div class="file-card"><span>📁</span>Documents</div><div class="file-card"><span>📁</span>Pictures</div><div class="file-card"><span>📁</span>Downloads</div><div class="file-card"><span>💾</span>Local Disk</div></div></div></div>';if(id==='browser')return '<div class="browser"><div class="browser-bar"><button>←</button><input value="https://win11sim.local/"><button onclick="toast(\'Navigation is simulated.\')">↵</button></div><div class="browser-content"><div style="font-size:50px">🌐</div><h1>Welcome to Browser</h1><p>This is a simulated browser inside the Windows 11 desktop.</p></div></div>';if(id==='notepad')return '<div class="notepad"><textarea placeholder="Type something..."></textarea></div>';if(id==='calculator')return '<div class="calc"><input class="calc-display" readonly value="0"><div class="calc-grid">'+['C','⌫','÷','×','7','8','9','−','4','5','6','+','1','2','3','=','0','.','(',')'].map(x=>`<button data-calc="${x}">${x}</button>`).join('')+'</div></div>';if(id==='photos')return '<div class="photos"><h2>Photos</h2><div class="gallery">🌄 🌌 🌲 🏔️ 🌊 🌅</div></div>';if(id==='store')return '<div class="store"><h2>Microsoft Store</h2><p>Discover apps in this simulated store.</p><div class="store-card">🎮 Games <button onclick="toast(\'Browsing simulated\')">Explore</button></div><div class="store-card">🛠️ Utilities <button onclick="toast(\'No real downloads\')">Explore</button></div></div>';if(id==='settings')return `<div class="settings"><h2>Settings</h2><div class="settings-row">🎨 Personalization <button onclick="toast('Personalization changed')">Dark</button></div><div class="settings-row">🔔 Notifications <span>On</span></div><div class="settings-row">👤 Account <span>${account.name}</span></div><div class="settings-row">ℹ️ System <span>Windows 11 Simulator</span></div></div>`;return '<div class="recycle"><div style="font-size:70px;margin-top:40px">♻️</div><h2>Recycle Bin is empty</h2><p>Deleted simulator items would appear here.</p></div>'}
function openApp(id){hide($('#startMenu'));hide($('#searchPanel'));hide($('#quickPanel'));let old=$(`.window[data-app="${id}"]`);if(old){show(old);old.style.zIndex=++z;return}let a=apps[id],w=document.createElement('section');w.className='window';w.dataset.app=id;w.style.zIndex=++z;w.innerHTML=`<div class="window-head"><div class="window-title"><span>${a[1]}</span>${a[0]}</div><div class="window-controls"><button data-min>−</button><button data-max>□</button><button class="close">×</button></div></div><div class="window-body">${body(id)}</div>`;$('#windows').append(w);w.onmousedown=()=>w.style.zIndex=++z;w.querySelector('.close').onclick=()=>w.remove();w.querySelector('[data-min]').onclick=()=>hide(w);w.querySelector('[data-max]').onclick=()=>w.classList.toggle('maximized');drag(w);if(id==='calculator')w.querySelectorAll('[data-calc]').forEach(b=>b.onclick=()=>calc(w,b.dataset.calc));let t=document.createElement('button');t.className='task-app';t.textContent=a[1];t.onclick=()=>openApp(id);$('#taskApps').append(t)}
let expression='';function calc(w,k){let d=w.querySelector('.calc-display');if(k==='C')expression='';else if(k==='⌫')expression=expression.slice(0,-1);else if(k==='='){try{if(!/^[0-9+\-*/().\s]+$/.test(expression))throw 0;expression=String(Function('return '+expression.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-'))())}catch{expression='Error'}}else expression+=k;d.value=expression||'0'}
function drag(w){let h=w.querySelector('.window-head'),on=0,x=0,y=0;h.onpointerdown=e=>{if(e.target.closest('button')||w.classList.contains('maximized'))return;let r=w.getBoundingClientRect();on=1;x=e.clientX-r.left;y=e.clientY-r.top;h.setPointerCapture(e.pointerId)};h.onpointermove=e=>{if(on){w.style.left=Math.max(4,e.clientX-x)+'px';w.style.top=Math.max(4,e.clientY-y)+'px'}};h.onpointerup=()=>on=0}
document.addEventListener('click',e=>{let o=e.target.closest('[data-open]');if(o)openApp(o.dataset.open)});
$('#startBtn').onclick=()=>{hide($('#searchPanel'));hide($('#quickPanel'));$('#startMenu').classList.toggle('hidden')};$('#searchBtn').onclick=()=>{hide($('#startMenu'));hide($('#quickPanel'));$('#searchPanel').classList.toggle('hidden');$('#globalSearch').focus()};$('#trayBtn').onclick=()=>{hide($('#startMenu'));hide($('#searchPanel'));$('#quickPanel').classList.toggle('hidden')};$('#quickSettings').onclick=()=>{hide($('#quickPanel'));openApp('settings')};$('#powerButton').onclick=()=>{hide($('#startMenu'));hide($('#os'));loginScreen()};
function search(q,target){q=q.toLowerCase();target.innerHTML=Object.entries(apps).filter(([id,a])=>(id+a[0]).toLowerCase().includes(q)).map(([id,a])=>`<button class="search-result" data-open="${id}"><span>${a[1]}</span><b>${a[0]}</b></button>`).join('')||'<p>No results found.</p>'}$('#startSearch').oninput=e=>search(e.target.value,$('#pinnedApps'));$('#globalSearch').oninput=e=>search(e.target.value,$('#searchResults'));
$('#desktop').oncontextmenu=e=>{e.preventDefault();let m=$('#contextMenu');m.style.left=e.clientX+'px';m.style.top=e.clientY+'px';show(m)};document.onclick=e=>{if(!e.target.closest('#contextMenu'))hide($('#contextMenu'));let c=e.target.closest('[data-context]');if(c){hide($('#contextMenu'));if(c.dataset.context==='refresh')toast('Desktop refreshed');else openApp('settings')}};
$('#brightness').oninput=e=>$('#os').style.filter=`brightness(${e.target.value}%)`;$('#volume').oninput=e=>toast('Volume '+e.target.value+'%');function toast(t){let x=$('#toast');x.textContent=t;show(x);clearTimeout(window.to);window.to=setTimeout(()=>hide(x),2200)}function clock(){let d=new Date();$('#clock b').textContent=d.toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});$('#clock small').textContent=d.toLocaleDateString()}setInterval(clock,1000);clock();
